table Fact1
	lineageTag: 8d2a8384-9039-405b-999a-c6f26e9e2bd6

	column Cat
		dataType: string
		lineageTag: a4adf18d-5e2d-4497-9b00-dd1872fcaa3f
		summarizeBy: none
		sourceColumn: Cat

		annotation SummarizationSetBy = Automatic

	column 'Sub Cat'
		dataType: string
		lineageTag: 8d105abc-7834-402f-a868-9a4add5112c5
		summarizeBy: none
		sourceColumn: Sub Cat

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: b3b8ad6a-2a38-4c83-8dd6-e71f12a510f1
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Fact1 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSlTSUUoCYkMDA6VYnWilZCA7BcQ3BfJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Column3 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Cat"}, {"Column2", "Sub Cat"}, {"Column3", "Value"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

